version: "3.8"
services:
  warehouse-database:
    container_name: warehouse-database
    environment:
      - MYSQL_DATABASE=warehouse
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
    image: mysql:8.0.21
    ports:
      - 3306:3306
    volumes:
      - warehouse-database:/var/lib/mysql
volumes:
  warehouse-database: